[package]
name = "deploy"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.29"
tempfile = "3.17.0"
tree-sitter = "0.25.1"
tree-sitter-go = "0.23.4"
walkdir = "2.5.0"

[build-dependencies]
cc="*"
